### PR TITLE
performance optimization

### PR DESCRIPTION
**Pull request by maksimru**
Current implementation invokes class loading on each token extraction/generation. Which leads to thread locks and poor performance on high scale.
> paseto builder: Improves performance by separating token builder and paseto builder, so paseto builder can be build in advance, and then reused for each token generation
> paseto parser : Boots crypto providers in advance and passes them to parser explicitly

### CODE REVIEW

**Comment by bdemers** [comment]
@maksimru did you mean to close this?

**Comment by maksimru** [comment]
@bdemers let's close for now, I made a pull request too early

**Comment by maksimru** [comment]
I will make another one later :)

**Comment by bdemers** [comment]
Sounds good!

**Pull request closed without merging**
